### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by tonnic** [LowieGoossens/octolabel#2]
Anyone have pictures/videos to show what this does?

**Comment by LowieGoossens** [comment]
In our environment, this plugin makes it possible to print a label with a brother label printer each time a print is ready.
On this label stands the name of the printer so we know to witch printbed we have to go to collect a print. And the name of the printed file so we know for who the print is. We put it then in a bag with the label.

**Comment by 6ffm70** [comment]
A picture of a printed (example) label in readme.md would be nice!

**Comment by LowieGoossens** [comment]
I will ad an example 👍
