### ISSUE TITLE
Question - Can this be utilized for multiple octoprints?

### ISSUE THREAD

**Issue by tonnic** [LowieGoossens/octolabel#4]
Sorry if this is a dumb question - Is there a way that the single printer can be sent prints from other octoprints as well? 

Ie - I have 1 brother printer, 3 octoprint printers and 3 different 3d printers.   Can this send label prints on the one printer, or would I need 3 brother label printers?

**Comment by LowieGoossens** [comment]
Yes, In my setup we have 12 different Octoprints and only one brother label printer.
