### ISSUE TITLE
Need a little help

### ISSUE THREAD

**Issue by tonnic** [LowieGoossens/octolabel#5]
Hi - Sorry I keep posting comments here :D.   I need some help.  I installed the plugin and have my QL-700 plugged into the Octopi server.  

Bus 001 Device 005: ID 04f9:2042 Brother Industries, Ltd

I have the plugin enabled and have the IP of the octopi server set there.  I have printing cancelled and printing done enabled, but when I start a print and cancel it, the label maker does not print anything.

**Comment by LowieGoossens** [comment]
Hi did you install the zipped api (directory label print api) in the seperated folder on the same raspberry or other platform that you are using for running your octoprint?
I installed it on a seperate raspbery.
The ip you must enter is the same ip adress as you set up by installing the label_print_api so not the ip adres of your ocoptopi.

**Comment by tonnic** [comment]
I saw the zip but thought it was included in the installation with the way it was worded. Where does the zip file go?  Do I just install it the same with the plugin manager?

**Comment by LowieGoossens** [comment]
In this zip file you find the code for operating the label printer this code isn't installed with the plugin manager, you need to follow the readme file in the zip file in order to instal this code

**Comment by tonnic** [comment]
> In this zip file you find the code for operating the label printer this code isn't installed with the plugin manager, you need to follow the readme file in the zip file in order to instal this code

If there is a way that you can update your documentation to include more specific instructions, that would be great :).  I'll install it in the meantime, but I think a lot of people would benefit from instructions.   BTW - I think the plugin is so cool that I bought the QL-700 just specifically because of this plugin ;)

**Comment by LowieGoossens** [comment]
I will update my documentation :)

**Comment by LowieGoossens** [comment]
One small question: do you also run this plugin on a raspberry? 
I run this plugin on a raspberry and on a mac but on the raspberry i found a bug in the latest release that i try to fix now

**Comment by tonnic** [comment]
> One small question: do you also run this plugin on a raspberry?
> I run this plugin on a raspberry and on a mac but on the raspberry i found a bug in the latest release that i try to fix now

So what I'm *attempting* to do :D, is to run the actual label_print_api on my windows machine (so I can print other labels as needed) and then have the octoprint servers (via raspberry pi) connect to the windows service, but I haven't had any luck yet.

I believe that the QL-700 should be have the parameter --printer usb://0x04f9:0x2042, but I can't get it to work...

**Comment by tonnic** [comment]
> I will update my documentation :)

Awesome ;).  Also, for example, I have no clue what 'brother_ql info labels' is used for or where that information goes.

**Comment by LowieGoossens** [comment]
Do you mean BROTHER_QL_LABEL = "62"? this setting is used to send to the label printer I think most important is the difference between the die-cut and endless labels

**Comment by LowieGoossens** [comment]
I found it in my documentation :) this are all possible values you can enter in BROTHER_QL_LABEL = "62" in the label_api file in the directory namebadge, in the label api.

**Comment by tonnic** [comment]
> I found it in my documentation :) this are all possible values you can enter in BROTHER_QL_LABEL = "62" in the label_api file in the directory namebadge, in the label api.

Does that mean that if I have BROTHER_QL_LABEL = "29x90" in the "__init__.py" (there was no label_api file in the namebadge directory) that I don't need to worry what is showing in the:

#LABEL_SIZE = (696, 756)
LABEL_SIZE = (756, 696)
#LABEL_SIZE = (413, 413)
FONT_SCALING = 4.2
#FONT_SCALING = 4.2*0.593


??   

Also - do you have a discord or something you can help me get this setup?

**Comment by LowieGoossens** [comment]
LABEL_SIZE = (306, 991) or LABEL_SIZE = ( 991, 306) if you use the 29x60 label this is the pixel size the software uses to create a label. (I said the wrong directory). When i set it up i changed both but i don't know if it is needed.

I'am not familiar with discord.

**Comment by tonnic** [comment]
> LABEL_SIZE = (306, 991) or LABEL_SIZE = ( 991, 306) if you use the 29x60 label this is the pixel size the software uses to create a label. (I said the wrong directory). When i set it up i changed both but i don't know if it is needed.
> 
> I'am not familiar with discord.

Can you update your documentation to show actual configuration examples.   ie -- for the IP of the label_api, is it just IP or IP:port, etc...  working config really helps to see what we are doing wrong.

**Comment by tonnic** [comment]
> LABEL_SIZE = (306, 991) or LABEL_SIZE = ( 991, 306) if you use the 29x60 label this is the pixel size the software uses to create a label. (I said the wrong directory). When i set it up i changed both but i don't know if it is needed.
> 
> I'am not familiar with discord.

I think that the plugin is cool, but the documentation isn't that clear... you know what you know, but I don't :).  I just want to get the plugin to work.

**Comment by tonnic** [comment]
> LABEL_SIZE = (306, 991) or LABEL_SIZE = ( 991, 306) if you use the 29x60 label this is the pixel size the software uses to create a label. (I said the wrong directory). When i set it up i changed both but i don't know if it is needed.
> 
> I'am not familiar with discord.

When I am looking at the label_api console I get the following:

WARNING:brother_ql.raster:Trying to switch the operating mode on a printer that doesn't support the command.
WARNING:brother_ql.raster:Trying to switch the operating mode on a printer that doesn't support the command.
DEBUG:brother_ql.raster:raster_image_size: 720x991
192.168.86.102 - - [27/Mar/2021 20:45:01] "GET /api/print/namebadge HTTP/1.1" 200 55

Here is my __init__.py

[__init__.py.txt](https://github.com/LowieGoossens/octolabel/files/6216776/__init__.py.txt)

**Comment by LowieGoossens** [comment]
why did you use this (raster_image_size: 720x991) label size?
I think it shoud be LABEL_SIZE = (306, 991) en then you shoud check if it is 90 degree rotated or not

**Comment by LowieGoossens** [comment]
I am working on the documentation :)

**Comment by LowieGoossens** [comment]
Or did the software change it to this value?

**Comment by LowieGoossens** [comment]
I did change the readme file, if you have more suggestions for changes let me know ;)

**Comment by tonnic** [comment]
> Or did the software change it to this value?

No, I included my namebadge python script.

Also - your documentation only refers to the label_api... any chance you can review the label_api.bat to see if that needs changes, as I have it on my windows machine so I can print labels from my computer at any time too.

**Comment by tonnic** [comment]
> I did change the readme file, if you have more suggestions for changes let me know ;)

This part could be a little confusing to some:

Run:

./label_api --help
# for example:
./label_api --port 8080 --model QL-800 --printer usb://0x04f9:0x2015 --backend pyusb

If we are not supposed to change the port, then you should change the 8080 to 8765 even in your example.

**Comment by LowieGoossens** [comment]
> > I did change the readme file, if you have more suggestions for changes let me know ;)
> 
> This part could be a little confusing to some:
> 
> Run:
> 
> ./label_api --help
> 
> # for example:
> ./label_api --port 8080 --model QL-800 --printer usb://0x04f9:0x2015 --backend pyusb
> 
> If we are not supposed to change the port, then you should change the 8080 to 8765 even in your example.

Yes this is true, i will rewrite this.

**Comment by LowieGoossens** [comment]
> > Or did the software change it to this value?
> 
> No, I included my namebadge python script.
> 
> Also - your documentation only refers to the label_api... any chance you can review the label_api.bat to see if that needs changes, as I have it on my windows machine so I can print labels from my computer at any time too.

label_api.bat is only a startup script. But I think I must change that file because it saids
python.exe label_api --model QL-800 --backend pyusb --printer usb://0x04f9:0x209b
and it shoud be 
python.exe label_api

**Comment by LowieGoossens** [comment]
I did change the bat file, did you get it working?

**Comment by tonnic** [comment]
> I did change the bat file, did you get it working?

I am still getting this (on windows).  I definitely changed the \label_plugins\namebadge\__init__.py
 - BROTHER_QL_LABEL = "29x90"
 - LABEL_SIZE = (991, 306)




WARNING:brother_ql.raster:Trying to switch the operating mode on a printer that doesn't support the command.
WARNING:brother_ql.raster:Trying to switch the operating mode on a printer that doesn't support the command.
DEBUG:brother_ql.raster:raster_image_size: 720x991

**Comment by tonnic** [comment]
I just bought some  62         696           62mm endless labels as well, but I'd like to use both if I needed.

**Comment by LowieGoossens** [comment]
Did you try to change the value to 720x991 in init.py maybe it is a little bit different with your printer?
I never had that warning, have you used the python test script to verify if it prints labels?
The 62mm endless tape worked perfect without changing the values only the labels are quitte big.
Good luck!

**Comment by tonnic** [comment]
> Did you try to change the value to 720x991 in init.py maybe it is a little bit different with your printer?
> I never had that warning, have you used the python test script to verify if it prints labels?
> The 62mm endless tape worked perfect without changing the values only the labels are quitte big.
> Good luck!

Which test script?  I can try that.

**Comment by LowieGoossens** [comment]
https://github.com/LowieGoossens/octolabel/blob/master/test_code/test.py

**Comment by LowieGoossens** [comment]
If you change the ip-address it will work normally, with this script you can see the answer on your request and if their is an error you will see it there.

**Comment by tonnic** [comment]
> If you change the ip-address it will work normally, with this script you can see the answer on your request and if their is an error you will see it there.

Traceback (most recent call last):
  File "E:\Octoprint_Label_API\test.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by tonnic** [comment]
> https://github.com/LowieGoossens/octolabel/blob/master/test_code/test.py

and where am I supposed to run this from....

**Comment by tonnic** [comment]
> Did you try to change the value to 720x991 in init.py maybe it is a little bit different with your printer?
> I never had that warning, have you used the python test script to verify if it prints labels?
> The 62mm endless tape worked perfect without changing the values only the labels are quitte big.
> Good luck!

Also, no I did not change anything in init.py other than 
- BROTHER _QL_LABEL
- LABEL_SIZE

[__init__.py.txt](https://github.com/LowieGoossens/octolabel/files/6217628/__init__.py.txt)

**Comment by LowieGoossens** [comment]
> > https://github.com/LowieGoossens/octolabel/blob/master/test_code/test.py
> 
> and where am I supposed to run this from....

I runned it from my laptop.

**Comment by LowieGoossens** [comment]
> > Did you try to change the value to 720x991 in init.py maybe it is a little bit different with your printer?
> > I never had that warning, have you used the python test script to verify if it prints labels?
> > The 62mm endless tape worked perfect without changing the values only the labels are quitte big.
> > Good luck!
> 
> Also, no I did not change anything in init.py other than
> 
> * BROTHER _QL_LABEL
> * LABEL_SIZE
> 
> [**init**.py.txt](https://github.com/LowieGoossens/octolabel/files/6217628/__init__.py.txt)

same

**Comment by tonnic** [comment]
> > > https://github.com/LowieGoossens/octolabel/blob/master/test_code/test.py
> > 
> > 
> > and where am I supposed to run this from....
> 
> I runned it from my laptop.

E:\Octoprint_Label_API>test.py
Traceback (most recent call last):
  File "E:\Octoprint_Label_API\test.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by LowieGoossens** [comment]
pip install requests

**Comment by LowieGoossens** [comment]
Did you get it working?

**Comment by tonnic** [comment]
No I did not...

**Comment by LowieGoossens** [comment]
I don't see what's going wrong here.
